version: "3.8"
services:
    landing-page:
        build: .
        environment:
            - VIRTUAL_HOST=engscitools.ca
        ports:
            - "5000:80"
        restart: unless-stopped
        network_mode: "bridge"